## THIS FILE IS AUTOMATICALLY GENERATED BY SCAFFOLDLY  ##
## CONFIG CAN BE CHANGED AT: https://start.scaffold.ly ##


module "github_stage_secrets_cool_sls_rest_api" {
  source  = "scaffoldly/stage-secrets/github"
  version = "1.0.0"

  for_each = module.aws_serverless_api_cool_sls_rest_api.stage_config

  stage           = each.key
  repository_name = "cool-sls-rest-api"

  secrets = {
    AWS_PARTITION                 = "aws"
    AWS_ACCOUNT_ID                = var.BOOTSTRAP_AWS_ACCOUNT_ID
    AWS_ACCESS_KEY_ID             = module.aws_serverless_api_cool_sls_rest_api.deployer_credentials.access_key
    AWS_SECRET_ACCESS_KEY         = module.aws_serverless_api_cool_sls_rest_api.deployer_credentials.secret_key
    AWS_REST_API_ID               = each.value.api_id
    AWS_REST_API_ROOT_RESOURCE_ID = each.value.api_resource_id
    AWS_WEBSOCKET_API_ID          = each.value.websocket_api_id
  }

  depends_on = [
    module.aws_serverless_api_cool_sls_rest_api
  ]
}
