## THIS FILE IS AUTOMATICALLY GENERATED BY SCAFFOLDLY  ##
## CONFIG CAN BE CHANGED AT: https://start.scaffold.ly ##


variable "BOOTSTRAP_GITHUB_TOKEN" {
  type = string
}

provider "github" {
  token = var.BOOTSTRAP_GITHUB_TOKEN
  owner = var.BOOTSTRAP_ORGANIZATION
}
